// Copyright 2024 the Parley Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

use icu_properties::props::Script;
use crate::analysis::Boundary;

pub(crate) fn script_to_fontique(script: Script) -> fontique::Script {
    fontique::Script(*FONTIQUE_SCRIPT_TAGS.get(script.to_icu4c_value() as usize).unwrap_or(b"Zzzz"))
}

// TODO(conor) remove when tests are migrated over
pub(crate) fn boundary_swash_to_parley(boundary: swash::text::cluster::Boundary) -> Boundary {
    match boundary {
        swash::text::cluster::Boundary::None => Boundary::None,
        swash::text::cluster::Boundary::Word => Boundary::Word,
        swash::text::cluster::Boundary::Line => Boundary::Line,
        swash::text::cluster::Boundary::Mandatory => Boundary::Mandatory,
    }
}

pub(crate) fn script_to_harfrust(script: Script) -> harfrust::Script {
    harfrust::Script::from_iso15924_tag(harfrust::Tag::new(
        FONTIQUE_SCRIPT_TAGS.get(script.to_icu4c_value() as usize).unwrap_or(b"Zzzz"),
    ))
        .unwrap_or(harfrust::script::UNKNOWN)
}

pub(crate) fn locale_to_fontique(locale: icu::locale::LanguageIdentifier) -> Option<fontique::Language> {
    fontique::Language::try_from_locale_bytes(locale.to_string().as_bytes()).ok()
}

#[rustfmt::skip]
const FONTIQUE_SCRIPT_TAGS: [[u8; 4]; 193] = [
    *b"Zyyy", *b"Zinh", *b"Arab", *b"Armn", *b"Beng", *b"Bopo", *b"Cher", *b"Copt", *b"Cyrl",
    *b"Dsrt", *b"Deva", *b"Ethi", *b"Geor", *b"Goth", *b"Grek", *b"Gujr", *b"Guru", *b"Hani",
    *b"Hang", *b"Hebr", *b"Hira", *b"Knda", *b"Kana", *b"Khmr", *b"Laoo", *b"Latn", *b"Mlym",
    *b"Mong", *b"Mymr", *b"Ogam", *b"Ital", *b"Orya", *b"Runr", *b"Sinh", *b"Syrc", *b"Taml",
    *b"Telu", *b"Thaa", *b"Thai", *b"Tibt", *b"Cans", *b"Yiii", *b"Tglg", *b"Hano", *b"Buhd",
    *b"Tagb", *b"Brai", *b"Cprt", *b"Limb", *b"Linb", *b"Osma", *b"Shaw", *b"Tale", *b"Ugar",
    *b"Zzzz", *b"Bugi", *b"Glag", *b"Khar", *b"Sylo", *b"Talu", *b"Tfng", *b"Xpeo", *b"Bali",
    *b"Batk", *b"Zzzz", *b"Brah", *b"Cham", *b"Zzzz", *b"Zzzz", *b"Zzzz", *b"Zzzz", *b"Egyp",
    *b"Zzzz", *b"Zzzz", *b"Zzzz", *b"Hmng", *b"Hung", *b"Zzzz", *b"Java", *b"Kali", *b"Zzzz",
    *b"Zzzz", *b"Lepc", *b"Lina", *b"Mand", *b"Zzzz", *b"Mero", *b"Nkoo", *b"Orkh", *b"Perm",
    *b"Phag", *b"Phnx", *b"Plrd", *b"Zzzz", *b"Zzzz", *b"Zzzz", *b"Zzzz", *b"Zzzz", *b"Zzzz",
    *b"Vaii", *b"Zzzz", *b"Xsux", *b"Zzzz", *b"Zzzz", *b"Cari", *b"Zzzz", *b"Lana", *b"Lyci",
    *b"Lydi", *b"Olck", *b"Rjng", *b"Saur", *b"Sgnw", *b"Sund", *b"Zzzz", *b"Mtei", *b"Armi",
    *b"Avst", *b"Cakm", *b"Zzzz", *b"Kthi", *b"Mani", *b"Phli", *b"Phlp", *b"Zzzz", *b"Prti",
    *b"Samr", *b"Tavt", *b"Zzzz", *b"Zzzz", *b"Bamu", *b"Lisu", *b"Zzzz", *b"Sarb", *b"Bass",
    *b"Dupl", *b"Elba", *b"Gran", *b"Zzzz", *b"Zzzz", *b"Mend", *b"Merc", *b"Narb", *b"Nbat",
    *b"Palm", *b"Sind", *b"Wara", *b"Zzzz", *b"Zzzz", *b"Mroo", *b"Nshu", *b"Shrd", *b"Sora",
    *b"Takr", *b"Tang", *b"Zzzz", *b"Hluw", *b"Khoj", *b"Tirh", *b"Aghb", *b"Mahj", *b"Ahom",
    *b"Hatr", *b"Modi", *b"Mult", *b"Pauc", *b"Sidd", *b"Adlm", *b"Bhks", *b"Marc", *b"Newa",
    *b"Osge", *b"Zzzz", *b"Zzzz", *b"Zzzz", *b"Gonm", *b"Soyo", *b"Zanb", *b"Dogr", *b"Gong",
    *b"Maka", *b"Medf", *b"Rohg", *b"Sogd", *b"Sogo", *b"Elym", *b"Hmnp", *b"Nand", *b"Wcho",
    *b"Chrs", *b"Diak", *b"Kits", *b"Yezi",
];

// TODO(conor) only used in tests, remove after rework
pub(crate) fn icu_to_swash(icu_script: Script) -> Option<swash::text::Script> {
    match icu_script {
        Script::Adlam => Some(swash::text::Script::Adlam),
        Script::CaucasianAlbanian => Some(swash::text::Script::CaucasianAlbanian),
        Script::Ahom => Some(swash::text::Script::Ahom),
        Script::Arabic => Some(swash::text::Script::Arabic),
        Script::ImperialAramaic => Some(swash::text::Script::ImperialAramaic),
        Script::Armenian => Some(swash::text::Script::Armenian),
        Script::Avestan => Some(swash::text::Script::Avestan),
        Script::Balinese => Some(swash::text::Script::Balinese),
        Script::Bamum => Some(swash::text::Script::Bamum),
        Script::BassaVah => Some(swash::text::Script::BassaVah),
        Script::Batak => Some(swash::text::Script::Batak),
        Script::Bengali => Some(swash::text::Script::Bengali),
        Script::Bhaiksuki => Some(swash::text::Script::Bhaiksuki),
        Script::Bopomofo => Some(swash::text::Script::Bopomofo),
        Script::Brahmi => Some(swash::text::Script::Brahmi),
        Script::Braille => Some(swash::text::Script::Braille),
        Script::Buginese => Some(swash::text::Script::Buginese),
        Script::Buhid => Some(swash::text::Script::Buhid),
        Script::Chakma => Some(swash::text::Script::Chakma),
        Script::CanadianAboriginal => Some(swash::text::Script::CanadianAboriginal),
        Script::Carian => Some(swash::text::Script::Carian),
        Script::Cham => Some(swash::text::Script::Cham),
        Script::Cherokee => Some(swash::text::Script::Cherokee),
        Script::Chorasmian => Some(swash::text::Script::Chorasmian),
        Script::Coptic => Some(swash::text::Script::Coptic),
        Script::Cypriot => Some(swash::text::Script::Cypriot),
        Script::Cyrillic => Some(swash::text::Script::Cyrillic),
        Script::Devanagari => Some(swash::text::Script::Devanagari),
        Script::DivesAkuru => Some(swash::text::Script::DivesAkuru),
        Script::Dogra => Some(swash::text::Script::Dogra),
        Script::Deseret => Some(swash::text::Script::Deseret),
        Script::Duployan => Some(swash::text::Script::Duployan),
        Script::EgyptianHieroglyphs => Some(swash::text::Script::EgyptianHieroglyphs),
        Script::Elbasan => Some(swash::text::Script::Elbasan),
        Script::Elymaic => Some(swash::text::Script::Elymaic),
        Script::Ethiopian => Some(swash::text::Script::Ethiopic),
        Script::Georgian => Some(swash::text::Script::Georgian),
        Script::Glagolitic => Some(swash::text::Script::Glagolitic),
        Script::GunjalaGondi => Some(swash::text::Script::GunjalaGondi),
        Script::MasaramGondi => Some(swash::text::Script::MasaramGondi),
        Script::Gothic => Some(swash::text::Script::Gothic),
        Script::Grantha => Some(swash::text::Script::Grantha),
        Script::Greek => Some(swash::text::Script::Greek),
        Script::Gujarati => Some(swash::text::Script::Gujarati),
        Script::Gurmukhi => Some(swash::text::Script::Gurmukhi),
        Script::Hangul => Some(swash::text::Script::Hangul),
        Script::Han => Some(swash::text::Script::Han),
        Script::Hanunoo => Some(swash::text::Script::Hanunoo),
        Script::Hatran => Some(swash::text::Script::Hatran),
        Script::Hebrew => Some(swash::text::Script::Hebrew),
        Script::Hiragana => Some(swash::text::Script::Hiragana),
        Script::AnatolianHieroglyphs => Some(swash::text::Script::AnatolianHieroglyphs),
        Script::PahawhHmong => Some(swash::text::Script::PahawhHmong),
        Script::NyiakengPuachueHmong => Some(swash::text::Script::NyiakengPuachueHmong),
        Script::OldHungarian => Some(swash::text::Script::OldHungarian),
        Script::OldItalic => Some(swash::text::Script::OldItalic),
        Script::Javanese => Some(swash::text::Script::Javanese),
        Script::KayahLi => Some(swash::text::Script::KayahLi),
        Script::Katakana => Some(swash::text::Script::Katakana),
        Script::Kharoshthi => Some(swash::text::Script::Kharoshthi),
        Script::Khmer => Some(swash::text::Script::Khmer),
        Script::Khojki => Some(swash::text::Script::Khojki),
        Script::KhitanSmallScript => Some(swash::text::Script::KhitanSmallScript),
        Script::Kannada => Some(swash::text::Script::Kannada),
        Script::Kaithi => Some(swash::text::Script::Kaithi),
        Script::TaiTham => Some(swash::text::Script::TaiTham),
        Script::Lao => Some(swash::text::Script::Lao),
        Script::Latin => Some(swash::text::Script::Latin),
        Script::Lepcha => Some(swash::text::Script::Lepcha),
        Script::Limbu => Some(swash::text::Script::Limbu),
        Script::LinearA => Some(swash::text::Script::LinearA),
        Script::LinearB => Some(swash::text::Script::LinearB),
        Script::Lisu => Some(swash::text::Script::Lisu),
        Script::Lycian => Some(swash::text::Script::Lycian),
        Script::Lydian => Some(swash::text::Script::Lydian),
        Script::Mahajani => Some(swash::text::Script::Mahajani),
        Script::Makasar => Some(swash::text::Script::Makasar),
        Script::Mandaic => Some(swash::text::Script::Mandaic),
        Script::Manichaean => Some(swash::text::Script::Manichaean),
        Script::Marchen => Some(swash::text::Script::Marchen),
        Script::Medefaidrin => Some(swash::text::Script::Medefaidrin),
        Script::MendeKikakui => Some(swash::text::Script::MendeKikakui),
        Script::MeroiticCursive => Some(swash::text::Script::MeroiticCursive),
        Script::MeroiticHieroglyphs => Some(swash::text::Script::MeroiticHieroglyphs),
        Script::Malayalam => Some(swash::text::Script::Malayalam),
        Script::Modi => Some(swash::text::Script::Modi),
        Script::Mongolian => Some(swash::text::Script::Mongolian),
        Script::Mro => Some(swash::text::Script::Mro),
        Script::MeeteiMayek => Some(swash::text::Script::MeeteiMayek),
        Script::Multani => Some(swash::text::Script::Multani),
        Script::Myanmar => Some(swash::text::Script::Myanmar),
        Script::Nandinagari => Some(swash::text::Script::Nandinagari),
        Script::OldNorthArabian => Some(swash::text::Script::OldNorthArabian),
        Script::Nabataean => Some(swash::text::Script::Nabataean),
        Script::Newa => Some(swash::text::Script::Newa),
        Script::Nko => Some(swash::text::Script::Nko),
        Script::Nushu => Some(swash::text::Script::Nushu),
        Script::Ogham => Some(swash::text::Script::Ogham),
        Script::OlChiki => Some(swash::text::Script::OlChiki),
        Script::OldTurkic => Some(swash::text::Script::OldTurkic),
        Script::Oriya => Some(swash::text::Script::Oriya),
        Script::Osage => Some(swash::text::Script::Osage),
        Script::Osmanya => Some(swash::text::Script::Osmanya),
        Script::Palmyrene => Some(swash::text::Script::Palmyrene),
        Script::PauCinHau => Some(swash::text::Script::PauCinHau),
        Script::OldPermic => Some(swash::text::Script::OldPermic),
        Script::PhagsPa => Some(swash::text::Script::PhagsPa),
        Script::InscriptionalPahlavi => Some(swash::text::Script::InscriptionalPahlavi),
        Script::PsalterPahlavi => Some(swash::text::Script::PsalterPahlavi),
        Script::Phoenician => Some(swash::text::Script::Phoenician),
        Script::Miao => Some(swash::text::Script::Miao),
        Script::InscriptionalParthian => Some(swash::text::Script::InscriptionalParthian),
        Script::Rejang => Some(swash::text::Script::Rejang),
        Script::HanifiRohingya => Some(swash::text::Script::HanifiRohingya),
        Script::Runic => Some(swash::text::Script::Runic),
        Script::Samaritan => Some(swash::text::Script::Samaritan),
        Script::OldSouthArabian => Some(swash::text::Script::OldSouthArabian),
        Script::Saurashtra => Some(swash::text::Script::Saurashtra),
        Script::SignWriting => Some(swash::text::Script::SignWriting),
        Script::Shavian => Some(swash::text::Script::Shavian),
        Script::Sharada => Some(swash::text::Script::Sharada),
        Script::Siddham => Some(swash::text::Script::Siddham),
        Script::Khudawadi => Some(swash::text::Script::Khudawadi),
        Script::Sinhala => Some(swash::text::Script::Sinhala),
        Script::Sogdian => Some(swash::text::Script::Sogdian),
        Script::OldSogdian => Some(swash::text::Script::OldSogdian),
        Script::SoraSompeng => Some(swash::text::Script::SoraSompeng),
        Script::Soyombo => Some(swash::text::Script::Soyombo),
        Script::Sundanese => Some(swash::text::Script::Sundanese),
        Script::SylotiNagri => Some(swash::text::Script::SylotiNagri),
        Script::Syriac => Some(swash::text::Script::Syriac),
        Script::Tagbanwa => Some(swash::text::Script::Tagbanwa),
        Script::Takri => Some(swash::text::Script::Takri),
        Script::TaiLe => Some(swash::text::Script::TaiLe),
        Script::NewTaiLue => Some(swash::text::Script::NewTaiLue),
        Script::Tamil => Some(swash::text::Script::Tamil),
        Script::Tangut => Some(swash::text::Script::Tangut),
        Script::TaiViet => Some(swash::text::Script::TaiViet),
        Script::Telugu => Some(swash::text::Script::Telugu),
        Script::Tifinagh => Some(swash::text::Script::Tifinagh),
        Script::Tagalog => Some(swash::text::Script::Tagalog),
        Script::Thaana => Some(swash::text::Script::Thaana),
        Script::Thai => Some(swash::text::Script::Thai),
        Script::Tibetan => Some(swash::text::Script::Tibetan),
        Script::Tirhuta => Some(swash::text::Script::Tirhuta),
        Script::Ugaritic => Some(swash::text::Script::Ugaritic),
        Script::Vai => Some(swash::text::Script::Vai),
        Script::WarangCiti => Some(swash::text::Script::WarangCiti),
        Script::Wancho => Some(swash::text::Script::Wancho),
        Script::OldPersian => Some(swash::text::Script::OldPersian),
        Script::Cuneiform => Some(swash::text::Script::Cuneiform),
        Script::Yezidi => Some(swash::text::Script::Yezidi),
        Script::Yi => Some(swash::text::Script::Yi),
        Script::ZanabazarSquare => Some(swash::text::Script::ZanabazarSquare),
        Script::Inherited => Some(swash::text::Script::Inherited),
        Script::Common => Some(swash::text::Script::Common),
        Script::Unknown => Some(swash::text::Script::Unknown),
        _ => None,
        // Script::CyproMinoan => Some(swash::text::Script::CyproMinoan),
        // Script::OldUyghur => Some(swash::text::Script::OldUyghur),
        // Script::Tangsa => Some(swash::text::Script::Tangsa),
        // Script::Toto => Some(swash::text::Script::Toto),
        // Script::Vithkuqi => Some(swash::text::Script::Vithkuqi),
        // Script::Kawi => Some(swash::text::Script::Kawi),
        // Script::NagMundari => Some(swash::text::Script::NagMundari),
        // Script::Nastaliq => Some(swash::text::Script::Nastaliq),
    }
}