// Copyright 2026 the Parley Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Checks that Parley makes the same first-line break decisions as Chrome.
//!
//! The expected data has been collected using the `linebreaking_browser` harness
//! and stored per font under `linebreaking_browser/data/<family>.csv`.
//!
//! For each font in [`FONTS`] and each seed we regenerate the input with `parley_linebreaking_cases`,
//! lay it out in that font with the width generated by Chrome, and assert Parley's first line holds
//! the same number of characters.
//! We need to match two specific Chrome behaviours:
//!
//! * Chrome quantizes `font-size` to 1/100px buckets by truncating.
//! * Chrome makes linebreaking decisions against a width which is 1/64th
//!   pixel wider than the given width constraint.
//!
//! We also have an issue due to Chrome's 16.16 fixed point measurement being slightly
//! narrower than our f32 result (at least for reasonably short texts).
//! For full details, see [`RESIDUAL_SLACK_SUBPIXELS`].

use core::fmt::Write;
use std::path::Path;
use std::sync::Arc;

use fontique::{Blob, Collection, CollectionOptions, SourceCache};
use parley::{FontContext, FontFamily, Layout, LayoutContext, StyleProperty};
use parley_linebreaking_cases::{Case, FONTS, PROBE_SUBPIXELS, SUBPIXELS_PER_PX};

/// If the matching with exactly Chrome's boundary fails, we try again with a very small
/// additional margin, to ensure that the cause is the accumulation unit mismatch (as
/// chrome works in 16.16 fixed point pixels).
///
/// The risk of this increases as text gets longer, but the absolute maximum drift
/// per glyph is `2^-16`, so even an unreasonable 1000 character line (~2^10 chars) would
/// still be expected to only have a drift of about `2^-6`px, i.e. 1/64px.
/// Therefore, an extra margin of 1/64px will correctly detect this for reasonable
/// texts.
///
/// In real-world code which needs to match Chrome, we expect that adding this margin
/// unconditionally would be safe. The chance of a real case falling exactly within
/// that 1/64px mismatch is negligible.
///
/// We validate the number of cases that fall within this boundary; for our dataset, we
/// expect it to be less than 2%, as we have lines of an average of ~30 characters, so
/// the average drift per line is 2^-17 * 30, so the likelihood of that falling
/// in the gap is around (30 * 2^-17) * 64 (~1.5%).
const RESIDUAL_SLACK_SUBPIXELS: i64 = 1;

/// A loaded row from the data file, generated using `linebreaking_browser`.
struct Expected {
    seed: u64,
    /// Tightened width in subpixels, or a sentinel '0' for overflow cases.
    width_subpixels: i64,
    /// Characters Chrome placed on the first line.
    first_line_chars: usize,
}

#[test]
fn chrome_linebreaking_roboto() {
    // If changing the residual count for either of these tests, ensure that
    // it's near 1.5%.
    check_font("Roboto", 17);
}

#[test]
fn chrome_linebreaking_arimo() {
    check_font("Arimo", 13);
}

fn check_font(font_family: &str, expected_residuals: u64) {
    let font = FONTS
        .iter()
        .find(|font| font.family == font_family)
        .unwrap();
    let expectations = load_expectations(font_family);
    assert!(
        !expectations.is_empty(),
        "no expectations loaded for {}",
        font.family
    );

    let mut collection = Collection::new(CollectionOptions {
        shared: false,
        system_fonts: false,
    });
    collection.register_fonts(Blob::new(Arc::new(font.bytes.to_vec())), None);
    let mut font_cx = FontContext {
        collection,
        source_cache: SourceCache::default(),
    };

    let mut layout_cx = LayoutContext::<()>::new();

    let mut failures = 0_u64;
    let mut residuals = 0_u64;
    let mut report = String::new();
    for expected in &expectations {
        let case = Case::from_seed(expected.seed);

        assert!(
            case.text.is_ascii(),
            "This code is not written to be robust against non-ASCII text, primarily to the DOM's use of UTF-16."
        );

        let mut builder = layout_cx.ranged_builder(&mut font_cx, &case.text, 1.0, false);
        builder.push_default(FontFamily::named(font.family));
        builder.push_default(StyleProperty::FontSize(chromium_quantized_font_size(
            case.font_size,
        )));
        let mut layout = builder.build(&case.text);

        if expected.width_subpixels == 0 {
            let chars = parley_first_line_chars(&mut layout, PROBE_SUBPIXELS);
            // Parley didn't break at the same character index as Chrome for overflowing text,
            // so record that failure.
            if chars != expected.first_line_chars {
                failures += 1;
                if failures <= 20 {
                    writeln!(
                        report,
                        "\
  seed {:>5}: overflow handled differently — Chrome {} chars, Parley {} chars
        text: {:?}",
                        expected.seed, expected.first_line_chars, chars, case.text,
                    )
                    .unwrap();
                }
            }
            continue;
        }

        // We first try breaking with a *too small* width. We know that Chrome would break here,
        // but we want to check that Parley does too.
        let too_small_chars = parley_first_line_chars(&mut layout, expected.width_subpixels);
        if too_small_chars == expected.first_line_chars {
            failures += 1;
            if failures <= 20 {
                writeln!(
                    report,
                    "\
seed {:>5}: Parley doesn't break when Chrome would — Chrome {} chars, Parley {} chars
      text: {:?}",
                    expected.seed, expected.first_line_chars, too_small_chars, case.text,
                )
                .unwrap();
            }
        }
        // Blink's line breaker fits each line against the LayoutUnit
        // available width plus one LayoutUnit epsilon of 1/64px.
        //
        // See `AvailableWidthToFit`
        // <https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/layout/inline/line_breaker.h;l=306-308;drc=e619a461ad0bb6c32c92dc22f6faf5f2ea42cb75>
        let normal_chars = parley_first_line_chars(&mut layout, expected.width_subpixels + 1);
        if normal_chars == expected.first_line_chars {
            // We got the same result for this case, so can move on to the next.
            continue;
        }
        // This is (almost certainly) a mismatch due to Chromium's use of 16.16 advances, whereas we use f32.
        // See docs on RESIDUAL_SLACK_SUBPIXELS for more.
        let slack_first_line_chars = parley_first_line_chars(
            &mut layout,
            expected.width_subpixels + 1 + RESIDUAL_SLACK_SUBPIXELS,
        );
        if slack_first_line_chars == expected.first_line_chars {
            residuals += 1;
            continue;
        }

        failures += 1;
        if failures <= 20 {
            writeln!(
                report,
                "\
seed {:>5}: font {:6.3}px, width {:.4}px — Chrome {} chars, Parley {normal_chars} chars
      text: {:?}",
                expected.seed,
                case.font_size,
                expected.width_subpixels as f64 / SUBPIXELS_PER_PX,
                expected.first_line_chars,
                case.text,
            )
            .unwrap();
        }
    }

    assert!(
        failures == 0,
        "{}: {failures} / {} seeds disagree with Chrome:\n{report}{}",
        font.family,
        expectations.len(),
        if failures > 20 {
            format!("  … and {} more\n", failures - 20)
        } else {
            String::new()
        }
    );
    assert_eq!(
        residuals, expected_residuals,
        "Number of cases different due to advance width units doesn't match recorded count."
    );
}

/// The number of characters of the first line when `layout` is broken at `width_subpixels` (in subpixels).
fn parley_first_line_chars(layout: &mut Layout<()>, width_subpixels: i64) -> usize {
    let max_advance = width_subpixels as f64 / SUBPIXELS_PER_PX;
    layout.break_all_lines(Some(max_advance as f32));

    let first_line = layout.get(0).expect("layout has at least one line");
    first_line.text_range().len()
}

/// Quantizes a font size the way Chromium does (LSR-804).
///
/// Blink's font cache is keyed on the font size truncated to 1/100px
/// (see `kFontSizePrecisionMultiplier` in Chromium). Matching this
/// truncation avoids our lines being wider than in the browser.
///
/// See <https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/fonts/font_description.cc;l=270-282;drc=e619a461ad0bb6c32c92dc22f6faf5f2ea42cb75>.
fn chromium_quantized_font_size(font_size: f32) -> f32 {
    (font_size * 100.0).floor() / 100.0
}

/// Parse `linebreaking_browser/data/<font>.csv`.
fn load_expectations(font_family: &str) -> Vec<Expected> {
    const HEADER: &str = "seed,width_subpixels,first_line_chars";
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("linebreaking_browser_recorder/data")
        .join(format!("{font_family}.csv"));
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));

    let mut expectations = Vec::new();
    // The file is CSV with a `#`-comment metadata frontmatter; see `output_csv` in
    // the `linebreaking_browser` harness for the format.
    for line in raw.lines() {
        let line = line.trim();
        if line.is_empty() || line == HEADER {
            continue;
        }
        if let Some(rest) = line.strip_prefix('#') {
            if let Some(rest) = rest.trim().strip_prefix("font_family:") {
                assert_eq!(
                    rest.trim(),
                    font_family,
                    "Saved CSV should be for correct font family."
                );
            }
            continue;
        }
        // Values are plain integers (no quoting), so we parse by hand rather than
        // pull in a CSV dependency.
        let cols: Vec<&str> = line.split(',').collect();
        assert_eq!(
            cols.len(),
            3,
            "expected 3 columns in {}, got {line:?}",
            path.display()
        );
        expectations.push(Expected {
            seed: cols[0].parse().expect("seed is an integer"),
            width_subpixels: cols[1].parse().expect("width_subpixels is an integer"),
            first_line_chars: cols[2].parse().expect("first_line_chars is an integer"),
        });
    }

    expectations.sort_unstable_by_key(|expected| expected.seed);
    expectations
}
