// Copyright 2026 the Parley Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Checks that Parley makes the same first-line break decisions as Chrome.
//!
//! The expected data has been collected using the `linebreaking_browser` harness
//! and stored per font under `linebreaking_browser/data/<family>.csv`.
//!
//! For each font in [`FONTS`] and each seed we regenerate the input with `parley_linebreaking_cases`,
//! lay it out in that font with the width generated by Chrome, and assert Parley's first line holds
//! the same number of characters. The comparison itself lives in `parley_linebreaking_cases`
//! (the `compare` feature), shared with the in-browser fuzzer; here we load the CSV corpus and
//! tally the results.
//!
//! We need to match two specific Chrome behaviours:
//!
//! * Chrome quantizes `font-size` to 1/100px buckets by truncating.
//! * Chrome makes linebreaking decisions against a width which is 1/64th
//!   pixel wider than the given width constraint.
//!
//! We also have an issue due to Chrome's 16.16 fixed point measurement being slightly
//! narrower than our f32 result (at least for reasonably short texts). For full details, see
//! [`RESIDUAL_SLACK_SUBPIXELS`](parley_linebreaking_cases::RESIDUAL_SLACK_SUBPIXELS).

use core::fmt::Write;
use std::path::Path;

use parley::LayoutContext;
use parley_linebreaking_cases::{
    Case, FONTS, Outcome, SUBPIXELS_PER_PX, compare_case, font_context,
};

/// A loaded row from the data file, generated using `linebreaking_browser`.
struct Expected {
    seed: u64,
    /// Tightened width in subpixels, or a sentinel '0' for overflow cases.
    width_subpixels: i64,
    /// Characters Chrome placed on the first line.
    first_line_chars: usize,
}

#[test]
fn chrome_linebreaking_roboto() {
    // If changing the residual count for either of these tests, ensure that
    // it's near 1.5%.
    check_font("Roboto", 13);
}

#[test]
fn chrome_linebreaking_arimo() {
    check_font("Arimo", 19);
}

fn check_font(font_family: &str, expected_residuals: u64) {
    let font = FONTS
        .iter()
        .find(|font| font.family == font_family)
        .unwrap();
    let expectations = load_expectations(font_family);
    assert!(
        !expectations.is_empty(),
        "no expectations loaded for {}",
        font.family
    );

    let mut font_cx = font_context(font);
    let mut layout_cx = LayoutContext::<()>::new();

    let mut failures = 0_u64;
    let mut residuals = 0_u64;
    let mut report = String::new();
    for expected in &expectations {
        let case = Case::from_seed(expected.seed);

        assert!(
            case.text.is_ascii(),
            "This code is not written to be robust against non-ASCII text, primarily to the DOM's use of UTF-16."
        );

        let comparison = compare_case(
            &mut font_cx,
            &mut layout_cx,
            font.family,
            &case,
            expected.width_subpixels,
            expected.first_line_chars,
        );

        // Parley kept Chrome's full first line at a strictly narrower width. When this happens
        // the reported Parley count equals Chrome's, hence both placeholders use the same value.
        if comparison.breaks_too_late {
            failures += 1;
            if failures <= 20 {
                writeln!(
                    report,
                    "\
seed {:>5}: Parley doesn't break when Chrome would — Chrome {} chars, Parley {} chars
      text: {:?}",
                    expected.seed, expected.first_line_chars, expected.first_line_chars, case.text,
                )
                .unwrap();
            }
        }

        match comparison.outcome {
            Outcome::Match => {}
            Outcome::Residual => residuals += 1,
            Outcome::Mismatch { parley_chars } => {
                failures += 1;
                if failures <= 20 {
                    if expected.width_subpixels == 0 {
                        writeln!(
                            report,
                            "\
  seed {:>5}: overflow handled differently — Chrome {} chars, Parley {} chars
        text: {:?}",
                            expected.seed, expected.first_line_chars, parley_chars, case.text,
                        )
                        .unwrap();
                    } else {
                        writeln!(
                            report,
                            "\
seed {:>5}: font {:6.3}px, width {:.4}px — Chrome {} chars, Parley {parley_chars} chars
      text: {:?}",
                            expected.seed,
                            case.font_size,
                            expected.width_subpixels as f64 / SUBPIXELS_PER_PX,
                            expected.first_line_chars,
                            case.text,
                        )
                        .unwrap();
                    }
                }
            }
        }
    }

    assert!(
        failures == 0,
        "{}: {failures} / {} seeds disagree with Chrome:\n{report}{}",
        font.family,
        expectations.len(),
        if failures > 20 {
            format!("  … and {} more\n", failures - 20)
        } else {
            String::new()
        }
    );
    assert_eq!(
        residuals, expected_residuals,
        "Number of cases different due to advance width units doesn't match recorded count."
    );
}

/// Parse `linebreaking_browser/data/<font>.csv`.
fn load_expectations(font_family: &str) -> Vec<Expected> {
    const HEADER: &str = "seed,width_subpixels,first_line_chars";
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("linebreaking_browser/data")
        .join(format!("{font_family}.csv"));
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));

    let mut expectations = Vec::new();
    // The file is CSV with a `#`-comment metadata frontmatter; see `output_csv` in
    // the `linebreaking_browser` harness for the format.
    for line in raw.lines() {
        let line = line.trim();
        if line.is_empty() || line == HEADER {
            continue;
        }
        if let Some(rest) = line.strip_prefix('#') {
            if let Some(rest) = rest.trim().strip_prefix("font_family:") {
                assert_eq!(
                    rest.trim(),
                    font_family,
                    "Saved CSV should be for correct font family."
                );
            }
            continue;
        }
        // Values are plain integers (no quoting), so we parse by hand rather than
        // pull in a CSV dependency.
        let cols: Vec<&str> = line.split(',').collect();
        assert_eq!(
            cols.len(),
            3,
            "expected 3 columns in {}, got {line:?}",
            path.display()
        );
        expectations.push(Expected {
            seed: cols[0].parse().expect("seed is an integer"),
            width_subpixels: cols[1].parse().expect("width_subpixels is an integer"),
            first_line_chars: cols[2].parse().expect("first_line_chars is an integer"),
        });
    }

    expectations.sort_unstable_by_key(|expected| expected.seed);
    expectations
}
