// Copyright 2026 the Parley Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Per-style inline box metrics.
//!
//! Every entry of the style table corresponds to an inline box (the root style being the block
//! container's "strut", see CSS 2 §10.8). This module resolves, once per layout, the metrics of
//! each of those boxes from the style's *primary* font and `line-height`, and computes the
//! baseline shift implied by its `vertical-align` relative to its parent.
//!
//! # Aligned subtrees
//!
//! CSS Inline Layout 3 §4.2.3 defines the *aligned subtree* of an inline box as that box together
//! with every descendant inline box whose `vertical-align` is parent-relative (`baseline`, `sub`,
//! `super`, `text-top`, `text-bottom`, `middle`, or a `<length>`/`<percentage>`), i.e. everything
//! that is aligned relative to its parent's baseline rather than to the line box. Boxes with
//! `vertical-align: top | bottom` are aligned to the line box instead, so each of them roots a new
//! aligned subtree. Within a subtree all baselines are fixed relative to each other, so its extents
//! can be accumulated relative to the root's baseline while the line is being built; the subtrees
//! are only positioned against each other, and the line box sized, once the line is complete.
//! See <https://drafts.csswg.org/css-inline-3/#aligned-subtree> and CSS 2 §10.8
//! <https://www.w3.org/TR/CSS22/visudet.html#line-height>.

use alloc::vec::Vec;

use fontique::{FontStyle, FontWeight, FontWidth, Query, QueryFamily};
use parley_engine::{FontInstance, FontMetrics, ShapedText};

use crate::resolve::{ResolveContext, ResolvedStyle};
use crate::style::Brush;
use crate::{
    AlignmentBaseline, BaselineShift, FontContext, FontData, InlineBox, LineHeight, VerticalAlign,
};

/// Metrics of the inline box generated by one style table entry.
///
/// All distances are in layout units and measured from the box's own baseline; `over`/`ascent`
/// extend upwards, `under`/`descent` downwards.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub(crate) struct StyleMetrics {
    /// Ascent of the first available font (the top of the content area).
    pub(crate) ascent: f32,
    /// Descent of the first available font (the bottom of the content area).
    pub(crate) descent: f32,
    /// x-height of the first available font, used by `vertical-align: middle`.
    pub(crate) x_height: f32,
    /// Distance from the baseline to the top of the line-height expanded inline box.
    pub(crate) over: f32,
    /// Distance from the baseline to the bottom of the line-height expanded inline box.
    pub(crate) under: f32,
    /// Resolved `line-height` (`over + under`).
    pub(crate) line_height: f32,
    /// Offset of this box's baseline above the baseline of its [aligned subtree's] root.
    ///
    /// [aligned subtree's]: Self::aligned_subtree
    pub(crate) baseline_offset: f32,
    /// [`Self::baseline_offset`] before quantization. Children accumulate their shifts from this
    /// so that rounding never compounds along the ancestor chain.
    pub(crate) exact_baseline_offset: f32,
    /// Style index of the root of the [aligned subtree] this box belongs to: `0` for the root
    /// inline box, or the nearest ancestor (or self) with `vertical-align: top | bottom`.
    ///
    /// [aligned subtree]: self#aligned-subtrees
    pub(crate) aligned_subtree: u16,
    /// Style index of the parent inline box (`0`, itself, for the root).
    pub(crate) parent: u16,
    /// The style's font size, against which `sub`/`super` of children are resolved.
    pub(crate) font_size: f32,
}

/// Resolve the [`StyleMetrics`] of every style in `styles`, in table order.
///
/// Relies on the style table being ordered parent-first (`style.parent <= index`), which both
/// style builders guarantee. `shaped_text` is the already shaped text of the layout, whose run
/// metrics are reused where a style's first available font was also used for shaping.
pub(crate) fn resolve_style_metrics<B: Brush>(
    rcx: &ResolveContext,
    fcx: &mut FontContext,
    styles: &[ResolvedStyle<B>],
    shaped_text: &ShapedText,
    quantize: bool,
    out: &mut Vec<StyleMetrics>,
) {
    out.clear();
    out.reserve(styles.len());

    let mut query = fcx.collection.query(&mut fcx.source_cache);
    // Styles that differ only in properties that do not affect font selection (brush, decoration,
    // spacing, ...) share one font lookup. The parent is checked first as it most often matches.
    let mut font_keys: Vec<(FontKey, FontMetrics)> = Vec::with_capacity(styles.len());

    for (index, style) in styles.iter().enumerate() {
        let key = FontKey::new(style);
        let parent_index = usize::from(style.parent);
        let cached = if parent_index < index && font_keys[parent_index].0 == key {
            Some(parent_index)
        } else {
            font_keys.iter().position(|(k, _)| *k == key)
        };
        let font_metrics = match cached {
            Some(cached) => font_keys[cached].1,
            None => first_available_font(&mut query, rcx, style)
                .and_then(|font| {
                    let variations = rcx.variations(style.font_variations).unwrap_or(&[]);
                    shaped_run_metrics(shaped_text, &font, style.font_size, variations).or_else(
                        || FontMetrics::from_font_instance(&font, style.font_size, variations),
                    )
                })
                .unwrap_or_else(|| fallback_metrics(style.font_size)),
        };
        font_keys.push((key, font_metrics));

        let line_height = match style.line_height {
            LineHeight::Absolute(value) => value,
            LineHeight::FontSizeRelative(value) => value * style.font_size,
            LineHeight::MetricsRelative(value) => {
                (font_metrics.ascent + font_metrics.descent + font_metrics.leading) * value
            }
        };

        let mut metrics = StyleMetrics::from_font(&font_metrics, line_height, quantize);
        metrics.parent = style.parent;
        metrics.font_size = style.font_size;

        debug_assert!(
            parent_index <= index,
            "style table must be ordered parent-first"
        );
        if index == 0 || parent_index >= index {
            // The root inline box (the strut).
            metrics.parent = index as u16;
            metrics.baseline_offset = 0.;
            metrics.exact_baseline_offset = 0.;
            metrics.aligned_subtree = 0;
        } else {
            let parent = &out[parent_index];
            let align = style.vertical_align;
            if align.is_line_relative() {
                metrics.baseline_offset = 0.;
                metrics.exact_baseline_offset = 0.;
                metrics.aligned_subtree = index as u16;
            } else {
                let shift = shift_from_parent(align, metrics.over, metrics.under, parent);
                metrics.exact_baseline_offset = parent.exact_baseline_offset + shift;
                metrics.baseline_offset = quantize_offset(metrics.exact_baseline_offset, quantize);
                metrics.aligned_subtree = parent.aligned_subtree;
            }
        }

        out.push(metrics);
    }
}

/// The properties of a style that determine its first available font and that font's metrics.
#[derive(Clone, Copy, PartialEq)]
struct FontKey {
    family: usize,
    variations: usize,
    size: u32,
    width: FontWidth,
    weight: FontWeight,
    style: FontStyle,
}

impl FontKey {
    fn new<B: Brush>(style: &ResolvedStyle<B>) -> Self {
        Self {
            family: style.font_family.id(),
            variations: style.font_variations.id(),
            size: style.font_size.to_bits(),
            width: style.font_width,
            weight: style.font_weight,
            style: style.font_style,
        }
    }
}

/// The metrics of a shaped run using `font` at `font_size`, if any: the shaper has then already
/// computed the metrics this style needs. Only used at the font's default variation location,
/// which covers the common non-variable-font case without re-resolving axes.
fn shaped_run_metrics(
    shaped_text: &ShapedText,
    font: &FontInstance,
    font_size: f32,
    variations: &[crate::FontVariation],
) -> Option<FontMetrics> {
    if !variations.is_empty() || !font.synthesis.variation_settings().is_empty() {
        return None;
    }
    let font_index = shaped_text.fonts().iter().position(|f| f == font)?;
    let coords = shaped_text.normalized_coords();
    shaped_text
        .runs()
        .iter()
        .find(|run| {
            run.font_index == font_index
                && run.font_size.to_bits() == font_size.to_bits()
                && coords[run.normalized_coords_range.clone()]
                    .iter()
                    .all(|c| c.to_bits() == 0)
        })
        .map(|run| run.font_metrics)
}

impl StyleMetrics {
    /// Build the box metrics from first available font metrics and a resolved `line-height`.
    ///
    /// The half-leading is distributed as in CSS 2 §10.8.1. With `quantize`, ascent and descent
    /// are rounded to whole pixels and the leading above the baseline is floored, mirroring how
    /// text runs are placed.
    pub(crate) fn from_font(font: &FontMetrics, line_height: f32, quantize: bool) -> Self {
        let (ascent, descent) = if quantize {
            (font.ascent.round(), font.descent.round())
        } else {
            (font.ascent, font.descent)
        };
        let half_leading = (line_height - (ascent + descent)) / 2.;
        let over = if quantize {
            ascent + half_leading.floor()
        } else {
            ascent + half_leading
        };
        let under = line_height - over;
        let x_height = font.x_height.unwrap_or(ascent * 0.5);
        Self {
            ascent,
            descent,
            x_height: if quantize { x_height.round() } else { x_height },
            over,
            under,
            line_height,
            baseline_offset: 0.,
            exact_baseline_offset: 0.,
            aligned_subtree: 0,
            parent: 0,
            font_size: 0.,
        }
    }
}

/// The baseline shift (positive upwards) of a box extending `over` above and `under` below its
/// baseline, relative to the baseline of its `parent` inline box, for a parent-relative
/// `vertical-align` value: the `alignment-baseline` offset plus the `baseline-shift`.
/// Line-relative values (`top`, `bottom`) yield no shift.
pub(crate) fn shift_from_parent(
    align: VerticalAlign,
    over: f32,
    under: f32,
    parent: &StyleMetrics,
) -> f32 {
    let alignment = match align.alignment {
        AlignmentBaseline::Baseline => 0.,
        AlignmentBaseline::TextTop => parent.ascent - over,
        AlignmentBaseline::TextBottom => under - parent.descent,
        AlignmentBaseline::Middle => parent.x_height / 2. - (over - under) / 2.,
    };
    let shift = match align.shift {
        BaselineShift::Length(length) => length,
        // Constants as used by WebKit and Blink.
        BaselineShift::Sub => -(parent.font_size / 5.),
        BaselineShift::Super => parent.font_size / 3.,
        BaselineShift::Top | BaselineShift::Bottom => 0.,
    };
    alignment + shift
}

/// Round a baseline offset to whole pixels when `quantize` is set. Applied once to the
/// accumulated offset (not per level) so the total error stays within half a pixel.
pub(crate) fn quantize_offset(offset: f32, quantize: bool) -> f32 {
    if quantize { offset.round() } else { offset }
}

/// Where an in-flow [`InlineBox`] sits relative to the baseline of its aligned subtree.
#[derive(Clone, Copy, Debug)]
pub(crate) struct InlineBoxPlacement {
    /// Style index of the aligned subtree root (see [`StyleMetrics::aligned_subtree`]).
    pub(crate) aligned_subtree: u16,
    /// Offset of the box's baseline above the subtree root's baseline.
    pub(crate) baseline_offset: f32,
    /// Height of the box above its baseline.
    pub(crate) ascent: f32,
    /// Height of the box below its baseline.
    pub(crate) descent: f32,
}

/// Resolve the parent-relative alignment of `inline_box` against the inline box of the style
/// containing it (`parent_style`).
///
/// A box without an explicit baseline sits on the baseline, i.e. it is all ascent. For
/// `vertical-align: top | bottom` the returned offset is relative to the parent's subtree, but
/// such boxes are positioned against the line box instead (see `Line::inline_box_y`).
pub(crate) fn inline_box_placement(
    inline_box: &InlineBox,
    parent_style: u16,
    style_metrics: &[StyleMetrics],
    quantize: bool,
) -> InlineBoxPlacement {
    let ascent = inline_box.baseline.unwrap_or(inline_box.height);
    let descent = inline_box.height - ascent;
    let parent = style_metrics
        .get(usize::from(parent_style))
        .copied()
        .unwrap_or_default();
    let shift = shift_from_parent(inline_box.vertical_align, ascent, descent, &parent);
    InlineBoxPlacement {
        aligned_subtree: parent.aligned_subtree,
        baseline_offset: quantize_offset(parent.exact_baseline_offset + shift, quantize),
        ascent,
        descent,
    }
}

/// Query the [first available font] of `style`: the first face of its font stack that is available
/// and has a glyph for U+0020 SPACE. If no face has one, the first face is used.
///
/// [first available font]: https://drafts.csswg.org/css-fonts-4/#first-available-font
fn first_available_font<B: Brush>(
    query: &mut Query<'_>,
    rcx: &ResolveContext,
    style: &ResolvedStyle<B>,
) -> Option<FontInstance> {
    let families = rcx.stack(style.font_family).unwrap_or(&[]);
    query.set_families(families.iter().copied().map(QueryFamily::Id));
    query.set_attributes(fontique::Attributes {
        width: style.font_width,
        weight: style.font_weight,
        style: style.font_style,
    });
    let mut first = None;
    let mut found = None;
    query.matches_with(|font| {
        let instance = FontInstance {
            font: FontData {
                data: font.blob.clone(),
                index: font.index,
            },
            synthesis: font.synthesis,
        };
        let has_space = font
            .charmap()
            .is_some_and(|charmap| charmap.map(' ').is_some());
        if has_space {
            found = Some(instance);
            fontique::QueryStatus::Stop
        } else {
            first.get_or_insert(instance);
            fontique::QueryStatus::Continue
        }
    });
    found.or(first)
}

/// Metrics to use when no font is available at all.
///
/// These roughly match common Latin fonts, so that a layout without fonts still has plausible
/// line heights.
fn fallback_metrics(font_size: f32) -> FontMetrics {
    FontMetrics {
        ascent: font_size * 0.8,
        descent: font_size * 0.2,
        leading: 0.,
        underline_offset: 0.,
        underline_size: 0.,
        strikethrough_offset: 0.,
        strikethrough_size: 0.,
        cap_height: None,
        x_height: None,
    }
}
