// Copyright 2026 the Parley Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Per-style inline box metrics.
//!
//! Every entry of the style table corresponds to an inline box (the root style being the block
//! container's "strut", see CSS 2 §10.8). This module resolves, once per layout, the metrics of
//! each of those boxes from the style's *primary* font and `line-height`, and computes the
//! baseline shift implied by its `vertical-align` relative to its parent.
//!
//! # Aligned subtrees
//!
//! CSS Inline Layout 3 §4.2.3 defines the *aligned subtree* of an inline box as that box together
//! with every descendant inline box whose `vertical-align` is parent-relative (`baseline`, `sub`,
//! `super`, `text-top`, `text-bottom`, `middle`, or a `<length>`/`<percentage>`), i.e. everything
//! that is aligned relative to its parent's baseline rather than to the line box. Boxes with
//! `vertical-align: top | bottom` are aligned to the line box instead, so each of them roots a new
//! aligned subtree. Within a subtree all baselines are fixed relative to each other, so its extents
//! can be accumulated relative to the root's baseline while the line is being built; the subtrees
//! are only positioned against each other, and the line box sized, once the line is complete.
//! See <https://drafts.csswg.org/css-inline-3/#aligned-subtree> and CSS 2 §10.8
//! <https://www.w3.org/TR/CSS22/visudet.html#line-height>.

use alloc::vec::Vec;

use fontique::{Query, QueryFamily};
use parley_engine::{FontInstance, FontMetrics};

use crate::resolve::{ResolveContext, ResolvedStyle};
use crate::style::Brush;
use crate::{AlignmentBaseline, BaselineShift, FontContext, FontData, LineHeight, VerticalAlign};

/// Metrics of the inline box generated by one style table entry.
///
/// All distances are in layout units and measured from the box's own baseline; `over`/`ascent`
/// extend upwards, `under`/`descent` downwards.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub(crate) struct StyleMetrics {
    /// Ascent of the first available font (the top of the content area).
    pub(crate) ascent: f32,
    /// Descent of the first available font (the bottom of the content area).
    pub(crate) descent: f32,
    /// x-height of the first available font, used by `vertical-align: middle`.
    pub(crate) x_height: f32,
    /// Distance from the baseline to the top of the line-height expanded inline box.
    pub(crate) over: f32,
    /// Distance from the baseline to the bottom of the line-height expanded inline box.
    pub(crate) under: f32,
    /// Resolved `line-height` (`over + under`).
    pub(crate) line_height: f32,
    /// Offset of this box's baseline above the baseline of its [aligned subtree's] root.
    ///
    /// [aligned subtree's]: Self::aligned_subtree
    pub(crate) baseline_offset: f32,
    /// Style index of the root of the [aligned subtree] this box belongs to: `0` for the root
    /// inline box, or the nearest ancestor (or self) with `vertical-align: top | bottom`.
    ///
    /// [aligned subtree]: self#aligned-subtrees
    pub(crate) aligned_subtree: u16,
}

/// Resolve the [`StyleMetrics`] of every style in `styles`, in table order.
///
/// Relies on the style table being ordered parent-first (`style.parent <= index`), which both
/// style builders guarantee.
pub(crate) fn resolve_style_metrics<B: Brush>(
    rcx: &ResolveContext,
    fcx: &mut FontContext,
    styles: &[ResolvedStyle<B>],
    quantize: bool,
    out: &mut Vec<StyleMetrics>,
) {
    out.clear();
    out.reserve(styles.len());

    let mut query = fcx.collection.query(&mut fcx.source_cache);

    for (index, style) in styles.iter().enumerate() {
        let font_metrics = first_available_font(&mut query, rcx, style)
            .and_then(|font| {
                FontMetrics::from_font_instance(
                    &font,
                    style.font_size,
                    rcx.variations(style.font_variations).unwrap_or(&[]),
                )
            })
            .unwrap_or_else(|| fallback_metrics(style.font_size));

        let line_height = match style.line_height {
            LineHeight::Absolute(value) => value,
            LineHeight::FontSizeRelative(value) => value * style.font_size,
            LineHeight::MetricsRelative(value) => {
                (font_metrics.ascent + font_metrics.descent + font_metrics.leading) * value
            }
        };

        let mut metrics = StyleMetrics::from_font(&font_metrics, line_height, quantize);

        let parent_index = usize::from(style.parent);
        debug_assert!(
            parent_index <= index,
            "style table must be ordered parent-first"
        );
        if index == 0 || parent_index >= index {
            // The root inline box (the strut).
            metrics.baseline_offset = 0.;
            metrics.aligned_subtree = 0;
        } else {
            let parent = &out[parent_index];
            let parent_style = &styles[parent_index];
            let align = style.vertical_align;
            if align.is_line_relative() {
                metrics.baseline_offset = 0.;
                metrics.aligned_subtree = index as u16;
            } else {
                let shift = metrics.shift_from_parent(align, parent, parent_style.font_size);
                metrics.baseline_offset = parent.baseline_offset + shift;
                metrics.aligned_subtree = parent.aligned_subtree;
            }
        }

        out.push(metrics);
    }
}

impl StyleMetrics {
    /// Build the box metrics from first available font metrics and a resolved `line-height`.
    ///
    /// The half-leading is distributed as in CSS 2 §10.8.1. With `quantize`, ascent and descent
    /// are rounded to whole pixels and the leading above the baseline is floored, mirroring how
    /// text runs are placed.
    pub(crate) fn from_font(font: &FontMetrics, line_height: f32, quantize: bool) -> Self {
        let (ascent, descent) = if quantize {
            (font.ascent.round(), font.descent.round())
        } else {
            (font.ascent, font.descent)
        };
        let half_leading = (line_height - (ascent + descent)) / 2.;
        let over = if quantize {
            ascent + half_leading.floor()
        } else {
            ascent + half_leading
        };
        let under = line_height - over;
        let x_height = font.x_height.unwrap_or(ascent * 0.5);
        Self {
            ascent,
            descent,
            x_height: if quantize { x_height.round() } else { x_height },
            over,
            under,
            line_height,
            baseline_offset: 0.,
            aligned_subtree: 0,
        }
    }

    /// The baseline shift (positive upwards) of this box relative to its parent's baseline for a
    /// parent-relative `vertical-align` value: the `alignment-baseline` offset plus the
    /// `baseline-shift`. Line-relative values (`top`, `bottom`) yield no shift.
    fn shift_from_parent(&self, align: VerticalAlign, parent: &Self, parent_font_size: f32) -> f32 {
        let alignment = match align.alignment {
            AlignmentBaseline::Baseline => 0.,
            AlignmentBaseline::TextTop => parent.ascent - self.over,
            AlignmentBaseline::TextBottom => self.under - parent.descent,
            AlignmentBaseline::Middle => parent.x_height / 2. - (self.over - self.under) / 2.,
        };
        let shift = match align.shift {
            BaselineShift::Length(length) => length,
            // Constants as used by WebKit and Blink.
            BaselineShift::Sub => -(parent_font_size / 5.),
            BaselineShift::Super => parent_font_size / 3.,
            BaselineShift::Top | BaselineShift::Bottom => 0.,
        };
        alignment + shift
    }
}

/// Query the [first available font] of `style`: the first face of its font stack that is available
/// and has a glyph for U+0020 SPACE. If no face has one, the first face is used.
///
/// [first available font]: https://drafts.csswg.org/css-fonts-4/#first-available-font
fn first_available_font<B: Brush>(
    query: &mut Query<'_>,
    rcx: &ResolveContext,
    style: &ResolvedStyle<B>,
) -> Option<FontInstance> {
    let families = rcx.stack(style.font_family).unwrap_or(&[]);
    query.set_families(families.iter().copied().map(QueryFamily::Id));
    query.set_attributes(fontique::Attributes {
        width: style.font_width,
        weight: style.font_weight,
        style: style.font_style,
    });
    let mut first = None;
    let mut found = None;
    query.matches_with(|font| {
        let instance = FontInstance {
            font: FontData {
                data: font.blob.clone(),
                index: font.index,
            },
            synthesis: font.synthesis,
        };
        let has_space = font
            .charmap()
            .is_some_and(|charmap| charmap.map(' ').is_some());
        if has_space {
            found = Some(instance);
            fontique::QueryStatus::Stop
        } else {
            first.get_or_insert(instance);
            fontique::QueryStatus::Continue
        }
    });
    found.or(first)
}

/// Metrics to use when no font is available at all.
///
/// These roughly match common Latin fonts, so that a layout without fonts still has plausible
/// line heights.
fn fallback_metrics(font_size: f32) -> FontMetrics {
    FontMetrics {
        ascent: font_size * 0.8,
        descent: font_size * 0.2,
        leading: 0.,
        underline_offset: 0.,
        underline_size: 0.,
        strikethrough_offset: 0.,
        strikethrough_size: 0.,
        cap_height: None,
        x_height: None,
    }
}
